<script>
data = [
{ text : "Agri-Ardenns", dept : 9},
{ text : "L'Ardennas", dept : 9},
{ text : "L'Union - édition Ardennns", dept : 9},
{ text : "La Semaine des Ardenns", dept : 9},
{ text : "La Thiérace", dept : 9},
{ text : "Le Courrier - La Gazete", dept : 9},
{ text : "Les Petites Affiches Matot Braie", dept : 9},
{ text : "La Dépêche du Midi - édition Arièg", dept : 10},
{ text : "La Dépêche du Midi Dimanche - édition Arièg", dept : 10},
{ text : "La Gazette Ariégeois", dept : 10},
{ text : "Le Petit Journal - Édition Arièg", dept : 10},
{ text : "L'Est Eclai", dept : 10},
{ text : "L'Est Eclair - Edition du dimanch", dept : 10},
{ text : "L'Est Eclair - Edition économique, juridique et sociale La lettre du 7ème jou", dept : 10},
{ text : "La Dépêche de l'Aub", dept : 10},
{ text : "La Revue Agricole de l'Aub", dept : 10},
{ text : "Les Petites Affiches Matot Braine", dept : 10},
{ text : "Libération Champagn", dept : 10},
{ text : "Libération Champagne - Edition du dimanch", dept : 10},
{ text : "11 - Aude", dept : 11},
{ text : "L'Echo du Languedoc", dept : 11},
{ text : "L'Indépendant - édition Aude", dept : 11},
{ text : "L'Indépendant Dimanche - édition Aude", dept : 11},
{ text : "La Croix du Midi Aude", dept : 11},
{ text : "La Dépêche du Midi - édition Aude", dept : 11},
{ text : "La Dépêche du Midi Dimanche - édition Aude", dept : 11},
{ text : "La Semaine du Minervois", dept : 11},
{ text : "Le Limouxin", dept : 11},
{ text : "Le Paysan du Midi", dept : 11},
{ text : "Le Petit Journal - Édition Aude", dept : 11},
{ text : "Midi Libre - édition Aude", dept : 11},
{ text : "Midi Libre Dimanche - édition Aude", dept : 11},
{ text : "Bulletin d'Espalio", dept : 12},
{ text : "Centre Presse de l'Aveyro", dept : 12},
{ text : "Centre Presse de l'Aveyron Dimanch", dept : 12},
{ text : "La Dépêche du Midi - édition Aveyro", dept : 12},
{ text : "La Dépêche du Midi Dimanche - edition Aveyro", dept : 12},
{ text : "La Volonté Paysann", dept : 12},
{ text : "Le Journal de Milla", dept : 12},
{ text : "Le Petit Journal - Édition Aveyro", dept : 12},
{ text : "Le Villefranchoi", dept : 12},
{ text : "Midi Libre - édition Aveyro", dept : 12},
{ text : "13 - Bouches-du-Rhône", dept : ""},
{ text : "L'Agriculteur Provençal", dept : ""},
{ text : "La Marseillaise", dept : ""},
{ text : "La Provence", dept : ""},
{ text : "Le Régional", dept : ""},
{ text : "Les Nouvelles Publications Economiques et Juridiques", dept : ""},
{ text : "TPBM - Semaine Provence", dept : ""},
{ text : "14 - Calvados", dept : ""},
{ text : "L'Agriculteur Normand", dept : ""},
{ text : "L'Eveil de Lisieux-Côte", dept : ""},
{ text : "L'Orne Combattante", dept : ""},
{ text : "La Manche Libre", dept : ""},
{ text : "La Renaissance - Le Bessin", dept : ""},
{ text : "La Voix - Le Bocage", dept : ""},
{ text : "Le Pays d'Auge", dept : ""},
{ text : "Les Nouvelles de Falaise", dept : ""},
{ text : "Liberté - Le Bonhomme Libre", dept : ""},
{ text : "Ouest France", dept : ""},
{ text : "15 - Cantal", dept : ""},
{ text : "L'Union du Cantal", dept : ""},
{ text : "La Dépêche d'Auvergne", dept : ""},
{ text : "La Montagne - Centre France", dept : ""},
{ text : "La Montagne Dimanche - édition Cantal", dept : ""},
{ text : "La Voix du Cantal", dept : ""},
{ text : "Le Réveil Cantalien", dept : ""},
{ text : "16 - Charente", dept : ""},
{ text : "La Charente Libre", dept : ""},
{ text : "La Vie Charentaise", dept : ""},
{ text : "Le Confolentais", dept : ""},
{ text : "Le Courrier Français édition Charente", dept : ""},
{ text : "Sud Ouest", dept : ""},
{ text : "17 - Charente-Maritime", dept : ""},
{ text : "L'Agriculteur Charentais", dept : ""},
{ text : "L'Angérien Libre", dept : ""},
{ text : "L'Hebdo de Charente-Maritime", dept : ""},
{ text : "La Haute Saintonge", dept : ""},
{ text : "Le Littoral de la Charente-Maritime", dept : ""},
{ text : "Le Phare de Ré", dept : ""},
{ text : "Sud Ouest", dept : ""},
{ text : "18 - Cher", dept : ""},
{ text : "L'Echo du Berry", dept : ""},
{ text : "L'Information Agricole du Cher", dept : ""},
{ text : "La Voix du Sancerrois", dept : ""},
{ text : "Le Berry Républicain", dept : ""},
{ text : "Le Berry Républicain Dimanche", dept : ""},
{ text : "19 - Corrèze", dept : ""},
{ text : "L'Union Paysanne", dept : ""},
{ text : "La Montagne - Centre France", dept : ""},
{ text : "La Montagne Dimanche - édition Corrèze", dept : ""},
{ text : "La Vie Corrézienne", dept : ""},
{ text : "21 - Côte-d'Or", dept : ""},
{ text : "Auxois Libre - Bourgogne Libre", dept : ""},
{ text : "Le Bien Public", dept : ""},
{ text : "Le Châtillonnais et l'Auxois", dept : ""},
{ text : "Le Journal du Palais", dept : ""},
{ text : "MaCommune.Info édition 21 - Côte-d'Or", dept : ""},
{ text : "Terres de Bourgogne", dept : ""},
{ text : "22 - Côtes-d'Armor", dept : ""},
{ text : "L'Echo de l'Armor et de l'Argoat", dept : ""},
{ text : "L'Hebdomadaire d'Armor", dept : ""},
{ text : "La Presse d'Armor", dept : ""},
{ text : "Le Courrier Indépendant", dept : ""},
{ text : "Le Penthièvre", dept : ""},
{ text : "Le Petit Bleu des Côtes d'Armor", dept : ""},
{ text : "Le Poher Hebdo", dept : ""},
{ text : "Le Télégramme", dept : ""},
{ text : "Le Trégor", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "Paysan Breton édition Côtes-d'Armor", dept : ""},
{ text : "Terra - Terragricoles de Bretagne", dept : ""},
{ text : "23 - Creuse", dept : ""},
{ text : "L'Echo du Berry", dept : ""},
{ text : "La Creuse Agricole et Rurale", dept : ""},
{ text : "La Montagne - Centre France", dept : ""},
{ text : "La Montagne Dimanche - édition Creuse", dept : ""},
{ text : "24 - Dordogne", dept : ""},
{ text : "L'Essor Sarladais", dept : ""},
{ text : "La Dordogne Libre", dept : ""},
{ text : "La Vie Economique du Sud-Ouest", dept : ""},
{ text : "Le Courrier Français édition Dordogne", dept : ""},
{ text : "Le Démocrate Indépendant", dept : ""},
{ text : "Réussir le Périgord", dept : ""},
{ text : "Sud Ouest", dept : ""},
{ text : "25 - Doubs", dept : ""},
{ text : "L'Est Républicain", dept : ""},
{ text : "L'Est Républicain Lundi", dept : ""},
{ text : "La Terre de Chez Nous", dept : ""},
{ text : "MaCommune.Info édition 25 -Doubs", dept : ""},
{ text : "26 - Drôme", dept : ""},
{ text : "Drôme Hebdo", dept : ""},
{ text : "Journal du Diois et de la Drôme", dept : ""},
{ text : "L'Agriculture Drômoise", dept : ""},
{ text : "L'Echo Drôme-Ardèche", dept : ""},
{ text : "L'Impartial de la Drôme", dept : ""},
{ text : "La Tribune", dept : ""},
{ text : "Le Crestois", dept : ""},
{ text : "Le Dauphiné Libéré", dept : ""},
{ text : "27 - Eure", dept : ""},
{ text : "Eure Infos", dept : ""},
{ text : "L'Eure Agricole", dept : ""},
{ text : "L'Eveil de Pont-Audemer", dept : ""},
{ text : "L'Eveil Normand", dept : ""},
{ text : "L'Impartial", dept : ""},
{ text : "La Dépêche (Evreux - Louviers - Verneuil)", dept : ""},
{ text : "Le Courrier de l'Eure", dept : ""},
{ text : "Le Démocrate Vernonnais", dept : ""},
{ text : "Le Réveil Normand", dept : ""},
{ text : "Paris Normandie", dept : ""},
{ text : "28 - Eure-et-Loir", dept : ""},
{ text : "Horizons Centre Ile-de-France (Edition Eure-et-Loir)", dept : ""},
{ text : "L'Action Républicaine", dept : ""},
{ text : "L'Echo de Brou", dept : ""},
{ text : "L'Echo Républicain", dept : ""},
{ text : "Le Perche", dept : ""},
{ text : "29 - Finistère", dept : ""},
{ text : "L'Hebdo du Finistère - Le Progrès de Cornouaille - Le Courrier du Léon", dept : ""},
{ text : "Le Poher Hebdo", dept : ""},
{ text : "Le Télégramme", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "Paysan Breton édition Finistère", dept : ""},
{ text : "Terra - Terragricoles de Bretagne", dept : ""},
{ text : "2A - Corse-du-Sud", dept : ""},
{ text : "Corse Matin", dept : ""},
{ text : "Informateur Corse Nouvelle", dept : ""},
{ text : "Journal Arritti", dept : ""},
{ text : "Le Journal de la Corse", dept : ""},
{ text : "Le Petit Bastiais", dept : ""},
{ text : "2B - Haute-Corse", dept : ""},
{ text : "Corse Matin", dept : ""},
{ text : "Informateur Corse Nouvelle", dept : ""},
{ text : "Journal Arritti", dept : ""},
{ text : "Le Journal de la Corse", dept : ""},
{ text : "Le Petit Bastiais", dept : ""},
{ text : "30 - Gard", dept : ""},
{ text : "Cévennes Magazine", dept : ""},
{ text : "La Croix du Midi Gard", dept : ""},
{ text : "La Gazette de Nîmes", dept : ""},
{ text : "La Liberté - L'Homme de Bronze - Le Commercial Provence", dept : ""},
{ text : "La Marseillaise", dept : ""},
{ text : "Le Commercial du Gard", dept : ""},
{ text : "Le Paysan du Midi", dept : ""},
{ text : "Le Républicain d'Uzès et du Gard", dept : ""},
{ text : "Le Réveil du Midi", dept : ""},
{ text : "Midi Libre - édition Gard", dept : ""},
{ text : "Midi Libre Dimanche - édition Gard", dept : ""},
{ text : "31 - Haute Garonne", dept : ""},
{ text : "L'Opinion Indépendante", dept : ""},
{ text : "La Dépêche du Midi - édition Haute-Garonne", dept : ""},
{ text : "La Dépêche du Midi Dimanche - édition Haute-Garonne", dept : ""},
{ text : "La Gazette du Comminges", dept : ""},
{ text : "La Gazette du Midi", dept : ""},
{ text : "La Voix du Midi", dept : ""},
{ text : "Le Petit Journal - Édition Haute-Garonne", dept : ""},
{ text : "32 - Gers", dept : ""},
{ text : "La Dépêche du Midi - édition Gers", dept : ""},
{ text : "La Dépêche du Midi Dimanche - édition Gers", dept : ""},
{ text : "La Voix du Gers", dept : ""},
{ text : "Le Petit Journal - Édition Gers", dept : ""},
{ text : "33 - Gironde", dept : ""},
{ text : "Echos Judiciaires Girondins", dept : ""},
{ text : "Haute Gironde Blaye", dept : ""},
{ text : "La Dépêche du Bassin", dept : ""},
{ text : "Le Courrier Français édition Gironde", dept : ""},
{ text : "Le Journal du Médoc", dept : ""},
{ text : "Le Républicain Sud Gironde", dept : ""},
{ text : "Le Résistant de Libourne", dept : ""},
{ text : "Sud Ouest", dept : ""},
{ text : "34 - Hérault", dept : ""},
{ text : "L'Agathois", dept : ""},
{ text : "L'Agglo-Rieuse", dept : ""},
{ text : "L'Hérault Juridique et Economique", dept : ""},
{ text : "La Croix du Midi Hérault", dept : ""},
{ text : "La Gazette de Montpellier", dept : ""},
{ text : "La Semaine du Minervois", dept : ""},
{ text : "Le Paysan du Midi", dept : ""},
{ text : "Le Petit Journal - Édition Hérault", dept : ""},
{ text : "Métropolitain - 7 Officiel", dept : ""},
{ text : "Midi Libre - édition Hérault", dept : ""},
{ text : "Midi Libre Dimanche - édition Hérault", dept : ""},
{ text : "35 - Ille-et-Vilaine", dept : ""},
{ text : "7 Jours - Les Petites Affiches de Bretagne", dept : ""},
{ text : "L'Eclaireur", dept : ""},
{ text : "L'Hebdomadaire d'Armor", dept : ""},
{ text : "La Chronique Républicaine", dept : ""},
{ text : "La Gazette de la Manche, d'Ille-et-Vilaine et Mayenne", dept : ""},
{ text : "Le Journal de Vitré", dept : ""},
{ text : "Le Pays Malouin", dept : ""},
{ text : "Les Infos Pays de Redon", dept : ""},
{ text : "Ouest-Franc", dept : ""},
{ text : "Paysan Breton édition Ille-et-Vilaine", dept : ""},
{ text : "Terra - Terragricoles de Bretagne", dept : ""},
{ text : "36 - Indr", dept : ""},
{ text : "L'Aurore Paysanne", dept : ""},
{ text : "L'Echo du Berr", dept : ""},
{ text : "La Nouvelle République du Centre-Oues", dept : ""},
{ text : "La Nouvelle République du Dimanche édition Indre", dept : ""},
{ text : "37 - Indre-et-Loir", dept : ""},
{ text : "L'Action Agricole de Tourain", dept : ""},
{ text : "La Nouvelle République du Centre-Oues", dept : ""},
{ text : "La Nouvelle République du Dimanche édition Indre et Loir", dept : ""},
{ text : "La Renaissance Lochois", dept : ""},
{ text : "Terre de Touraine", dept : ""},
{ text : "38 - Isèr", dept : ""},
{ text : "L'Esso", dept : ""},
{ text : "Le Dauphiné Libéré", dept : ""},
{ text : "Le Mémorial de l'Isère", dept : ""},
{ text : "Les Affiches de Grenoble et du Dauphiné", dept : ""},
{ text : "Terre Dauphinoise", dept : ""},
{ text : "39 - Jura", dept : ""},
{ text : "Le Jura Agricole et Rural", dept : ""},
{ text : "Le Progrès", dept : ""},
{ text : "Le Progrès Dimanche", dept : ""},
{ text : "Voix du Jura", dept : ""},
{ text : "40 - Landes", dept : ""},
{ text : "Le Courrier Français édition Landes", dept : ""},
{ text : "Le Sillon (Gers - Landes - Pyrénées)", dept : ""},
{ text : "Les Annonces Landaises", dept : ""},
{ text : "Les Petites Affiches Landaises", dept : ""},
{ text : "Sud Ouest", dept : ""},
{ text : "41 - Loir-et-Cher", dept : ""},
{ text : "Horizons Loir-et-Cher", dept : ""},
{ text : "La Nouvelle République du Centre-Ouest", dept : ""},
{ text : "La Nouvelle République du Dimanche édition Loir et Cher", dept : ""},
{ text : "La Renaissance du Loir-et-Cher", dept : ""},
{ text : "42 - Loire", dept : ""},
{ text : "L'Essor-Affiches", dept : ""},
{ text : "La Tribune - Le progrès", dept : ""},
{ text : "Le Pays Roannais", dept : ""},
{ text : "Paysans de la Loire", dept : ""},
{ text : "43 - Haute-Loire", dept : ""},
{ text : "L'Eveil de la Haute-Loire", dept : ""},
{ text : "La Haute-Loire Paysanne", dept : ""},
{ text : "La Montagne - Centre France", dept : ""},
{ text : "La Montagne Dimanche - édition Haute-Loire", dept : ""},
{ text : "La Ruche", dept : ""},
{ text : "La Tribune - Le Progrès", dept : ""},
{ text : "44 - Loire-Atlantique", dept : ""},
{ text : "L'Echo d'Ancenis et du Vignoble", dept : ""},
{ text : "L'Echo de l'Ouest édition Loire Atlantique", dept : ""},
{ text : "L'Echo de la Presqu'île Guérandaise et de Saint-Nazaire", dept : ""},
{ text : "L'Eclaireur", dept : ""},
{ text : "L'Hebdo de Sèvre et Maine", dept : ""},
{ text : "L'Informateur Judiciaire", dept : ""},
{ text : "Le Courrier du Pays de Retz", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Les Infos Pays de Redon", dept : ""},
{ text : "Loire-Atlantique Agricole", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "Presse Océan", dept : ""},
{ text : "45 - Loiret", dept : ""},
{ text : "L'Eclaireur du Gâtinais", dept : ""},
{ text : "La République du Centre", dept : ""},
{ text : "La République du Centre dimanche", dept : ""},
{ text : "Le Courrier du Loiret", dept : ""},
{ text : "Le Journal de Gien", dept : ""},
{ text : "Le Loiret Agricole et Rural", dept : ""},
{ text : "46 - Lot", dept : ""},
{ text : "La Dépêche du Midi - édition Lot", dept : ""},
{ text : "La Dépêche du Midi Dimanche - édition Lot", dept : ""},
{ text : "La Vie Quercynoise", dept : ""},
{ text : "Le Petit Journal - Édition Lot", dept : ""},
{ text : "47 - Lot-et-Garonne", dept : ""},
{ text : "La Dépêche du Midi - édition Lot-et-Garonne", dept : ""},
{ text : "La Dépêche du Midi Dimanche - édition Lot-et-Garonne", dept : ""},
{ text : "La Vie Economique du Sud-Ouest", dept : ""},
{ text : "Le Courrier Français édition Lot-et-Garonne", dept : ""},
{ text : "Le Petit Bleu d'Agen", dept : ""},
{ text : "Le Petit Bleu d'Agen - Dimanche", dept : ""},
{ text : "Le Petit Journal - Édition Lot-et-Garonne", dept : ""},
{ text : "Le Républicain", dept : ""},
{ text : "Sud Ouest", dept : ""},
{ text : "48 - Lozère", dept : ""},
{ text : "Le Réveil Lozère", dept : ""},
{ text : "Lozère Nouvelle", dept : ""},
{ text : "Midi Libre - édition Lozère", dept : ""},
{ text : "Midi Libre Dimanche - édition Lozère", dept : ""},
{ text : "49 - Maine-et-Loire", dept : ""},
{ text : "Haut Anjou", dept : ""},
{ text : "L'Anjou Agricole", dept : ""},
{ text : "L'Echo d'Ancenis et du Vignoble", dept : ""},
{ text : "Le Courrier de l'Ouest", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "50 - Manche", dept : ""},
{ text : "L'Agriculteur Normand", dept : ""},
{ text : "La Gazette de la Manche, d'Ille-et-Vilaine et Mayenne", dept : ""},
{ text : "La Manche Libre", dept : ""},
{ text : "La Presse de la Manche", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "51 - Marne", dept : ""},
{ text : "L'Union - Edition Marne", dept : ""},
{ text : "La Marne Agricole", dept : ""},
{ text : "Les Petites Affiches Matot Braine", dept : ""},
{ text : "52 - Haute-Marne", dept : ""},
{ text : "L'Affranchi de Chaumont", dept : ""},
{ text : "L'Avenir Agricole et Rural de la Haute-Marne", dept : ""},
{ text : "La Voix de la Haute-Marne", dept : ""},
{ text : "Le Journal de la Haute-Marne", dept : ""},
{ text : "Le Journal de la Haute-Marne Dimanche", dept : ""},
{ text : "53 - Mayenne", dept : ""},
{ text : "Agri 53", dept : ""},
{ text : "Haut Anjou", dept : ""},
{ text : "L'Avenir Agricole", dept : ""},
{ text : "Le Courrier de la Mayenne", dept : ""},
{ text : "Le Publicateur Libre", dept : ""},
{ text : "Ouest France", dept : ""},
{ text : "54 - Meurthe-et-Moselle", dept : ""},
{ text : "L'Est Républicain", dept : ""},
{ text : "L'Est Républicain Lundi", dept : ""},
{ text : "La Semaine édition Meurthe-et-Moselle", dept : ""},
{ text : "Le Paysan Lorrain", dept : ""},
{ text : "Le Républicain Lorrain", dept : ""},
{ text : "Les Tablettes Lorraines", dept : ""},
{ text : "55 - Meuse", dept : ""},
{ text : "L'Est Républicain", dept : ""},
{ text : "L'Est Républicain Lundi", dept : ""},
{ text : "La Vie Agricole de la Meuse", dept : ""},
{ text : "Meuse Echos", dept : ""},
{ text : "56 - Morbihan", dept : ""},
{ text : "L'Echo de la Presqu'île Guérandaise et de Saint-Nazaire", dept : ""},
{ text : "La Gazette du Centre Morbihan", dept : ""},
{ text : "Le Ploërmelais", dept : ""},
{ text : "Le Télégramme", dept : ""},
{ text : "Les Infos Pays de Redon", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "Paysan Breton édition Morbihan", dept : ""},
{ text : "Pontivy Journal", dept : ""},
{ text : "Terra - Terragricoles de Bretagne", dept : ""},
{ text : "57 - Moselle", dept : ""},
{ text : "L'Ami des Foyers Chrétiens", dept : ""},
{ text : "La Moselle Agricole", dept : ""},
{ text : "La Semaine édition Moselle", dept : ""},
{ text : "Le Républicain Lorrain", dept : ""},
{ text : "Les Affiches d'Alsace et de Lorraine", dept : ""},
{ text : "58 - Nièvre", dept : ""},
{ text : "Le Journal du Centre", dept : ""},
{ text : "Le Journal du Centre - Dimanche", dept : ""},
{ text : "Le Régional de Cosne et du Charitois", dept : ""},
{ text : "Terres de Bourgogne", dept : ""},
{ text : "59 - Nord", dept : ""},
{ text : "L'Indicateur des Flandres", dept : ""},
{ text : "L'Observateur de l'Avesnois", dept : ""},
{ text : "L'Observateur du Cambrésis", dept : ""},
{ text : "L'Observateur du Douaisis", dept : ""},
{ text : "L'Observateur du Valenciennois", dept : ""},
{ text : "La Croix du Nord", dept : ""},
{ text : "La Gazette Nord Pas-de-Calais", dept : ""},
{ text : "La Sambre", dept : ""},
{ text : "La Voix du Nord", dept : ""},
{ text : "Le Courrier de Fourmies", dept : ""},
{ text : "Le Journal des Flandres", dept : ""},
{ text : "Le Phare Dunkerquois", dept : ""},
{ text : "Liberté - Hebdo", dept : ""},
{ text : "Nord Eclair", dept : ""},
{ text : "Terres et Territoires", dept : ""},
{ text : "60 - Oise", dept : ""},
{ text : "L'Echo du Thelle", dept : ""},
{ text : "L'Observateur de Beauvais", dept : ""},
{ text : "L'Oise Agricole", dept : ""},
{ text : "Le Bonhomme Picard", dept : ""},
{ text : "Le Courrier Picard", dept : ""},
{ text : "Le Parisien - L'Oise Matin", dept : ""},
{ text : "Le Réveil de Neufchâtel", dept : ""},
{ text : "Oise Hebdo", dept : ""},
{ text : "61 - Orne", dept : ""},
{ text : "L'Agriculteur Normand", dept : ""},
{ text : "L'Orne Combattante", dept : ""},
{ text : "L'Orne Hebdo", dept : ""},
{ text : "Le Journal de l'Orne", dept : ""},
{ text : "Le Perche", dept : ""},
{ text : "Le Publicateur Libre", dept : ""},
{ text : "Le Réveil Normand", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "62 - Pas-de-Calais", dept : ""},
{ text : "L'Abeille de la Ternoise", dept : ""},
{ text : "L'Avenir de l'Artois", dept : ""},
{ text : "L'Echo de la Lys", dept : ""},
{ text : "L'Indépendant du Pas-de-Calais", dept : ""},
{ text : "L'Observateur de l'Arrageois", dept : ""},
{ text : "La Croix du Nord", dept : ""},
{ text : "La Gazette Nord Pas-de-Calais", dept : ""},
{ text : "La semaine dans le Boulonnais", dept : ""},
{ text : "La Voix du Nord", dept : ""},
{ text : "Le Journal de Montreuil", dept : ""},
{ text : "Le Réveil de Berck", dept : ""},
{ text : "Les Echos du Touquet", dept : ""},
{ text : "Nord Eclair", dept : ""},
{ text : "Nord Littoral", dept : ""},
{ text : "Terres et Territoires", dept : ""},
{ text : "63 - Puy-de-Dôme", dept : ""},
{ text : "L'Annonceur Légal d'Auvergne et du Centre", dept : ""},
{ text : "L'Auvergne Agricole", dept : ""},
{ text : "La Gazette de Thiers et d'Ambert", dept : ""},
{ text : "La Montagne - Centre France", dept : ""},
{ text : "La Montagne Dimanche - édition Puy-de-Dôme", dept : ""},
{ text : "La Ruche", dept : ""},
{ text : "Le Semeur Hebdo", dept : ""},
{ text : "Les Petites Affiches d'Auvergne et du Centre Réunis", dept : ""},
{ text : "64 - Pyrénées-Atlantiques", dept : ""},
{ text : "Herria", dept : ""},
{ text : "L'Eclair des Pyrénées", dept : ""},
{ text : "La République des Pyrénées", dept : ""},
{ text : "La Semaine du Pays Basque", dept : ""},
{ text : "Le Journal de Saint-Palais", dept : ""},
{ text : "Le Sillon (Gers - Landes - Pyrénées)", dept : ""},
{ text : "Les Petites Affiches Béarnaises et des Pyrénées-Atlantiques", dept : ""},
{ text : "Les Petites Affiches du Pays Basque et des Pyrénées-Atlantiques", dept : ""},
{ text : "Sud Ouest - Édition Pyrénées-Atlantique", dept : ""},
{ text : "65 - Hautes-Pyrénées", dept : ""},
{ text : "L'Essor Bigourdan", dept : ""},
{ text : "La Dépêche du Midi - édition Hautes-Pyrénées", dept : ""},
{ text : "La Dépêche du Midi Dimanche - édition Hautes-Pyrénées", dept : ""},
{ text : "La Montagne des Hautes-Pyrénées", dept : ""},
{ text : "La Nouvelle République des Pyrénées", dept : ""},
{ text : "La Semaine des Pyrénées", dept : ""},
{ text : "Le Petit Journal - Édition Hautes-Pyrénées", dept : ""},
{ text : "66 - Pyrénées-Orientales", dept : ""},
{ text : "L'Agri", dept : ""},
{ text : "L'Echo des Métiers", dept : ""},
{ text : "L'Indépendant - édition Catalan", dept : ""},
{ text : "L'Indépendant Dimanche - édition Catalan", dept : ""},
{ text : "La Croix du Midi Pyrénées-Orientales", dept : ""},
{ text : "La Semaine du Roussillon", dept : ""},
{ text : "Le Petit Journal - Édition Pyrénées-Orientales", dept : ""},
{ text : "Le Travailleur Catalan", dept : ""},
{ text : "Parjal", dept : ""},
{ text : "67 - Bas-Rhin", dept : ""},
{ text : "L'Ami du Peuple", dept : ""},
{ text : "L'Est Agricole et Viticole", dept : ""},
{ text : "Les Affiches d'Alsace et de Lorraine", dept : ""},
{ text : "Les Dernières Nouvelles d'Alsace", dept : ""},
{ text : "Les Dernières Nouvelles d'Alsace du Lundi", dept : ""},
{ text : "68 - Haut-Rhin", dept : ""},
{ text : "L'Alsace", dept : ""},
{ text : "L'Alsace du Lundi", dept : ""},
{ text : "L'Ami du Peuple", dept : ""},
{ text : "Le Journal des Ménagères", dept : ""},
{ text : "Les Dernières Nouvelles d'Alsace", dept : ""},
{ text : "Les Dernières Nouvelles d'Alsace du Lundi", dept : ""},
{ text : "Paysan du Haut-Rhin", dept : ""},
{ text : "Petites Affiches du Haut-Rhin", dept : ""},
{ text : "69 - Rhône", dept : ""},
{ text : "L'Essor", dept : ""},
{ text : "L'Information Agricole du Rhône", dept : ""},
{ text : "Le Journal du Bâtiment et des Travaux Publics", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Le Patriote Beaujolais", dept : ""},
{ text : "Le Pays d'Entre Loire et Rhône", dept : ""},
{ text : "Le Progrès", dept : ""},
{ text : "Les Echos", dept : ""},
{ text : "Tout Lyon Affiches", dept : ""},
{ text : "Tribune de Lyon", dept : ""},
{ text : "70 - Haute-Saône", dept : ""},
{ text : "L'Est Républicain", dept : ""},
{ text : "La Haute-Saône Agricole et Rural", dept : ""},
{ text : "La Presse de Gray", dept : ""},
{ text : "La Presse de Vesoul", dept : ""},
{ text : "Les Affiches de la Haute-Saône", dept : ""},
{ text : "71 - Saône-et-Loire", dept : ""},
{ text : "L'Exploitant Agricole", dept : ""},
{ text : "L'Indépendant du Louhannais et du Jura", dept : ""},
{ text : "La Renaissance", dept : ""},
{ text : "Le Journal de Saône-et-Loire", dept : ""},
{ text : "Le Pays Roannais", dept : ""},
{ text : "Nouvelles de Saône-et-Loire", dept : ""},
{ text : "72 - Sarthe", dept : ""},
{ text : "L'Écho de Vibraye", dept : ""},
{ text : "L'Orne Hebdo", dept : ""},
{ text : "Le Maine Libre", dept : ""},
{ text : "Le Perche", dept : ""},
{ text : "Le Petit Courrier - L'Echo de la Vallée du Loir", dept : ""},
{ text : "Les Alpes Mancelles Libérées", dept : ""},
{ text : "Les Nouvelles de Sablé - L'Echo Fléchois", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "Réussir Agri 72", dept : ""},
{ text : "73 - Savoie", dept : ""},
{ text : "Eco Savoie Mont blanc", dept : ""},
{ text : "L'Essor Savoyard", dept : ""},
{ text : "L'Hebdo des Savoie", dept : ""},
{ text : "La Maurienne", dept : ""},
{ text : "La Savoie", dept : ""},
{ text : "La Tarentaise Hebdo", dept : ""},
{ text : "La Vie Nouvelle", dept : ""},
{ text : "Le Dauphiné Libéré - édition Savoie", dept : ""},
{ text : "Le Journal du Bâtiment et des Travaux Publics", dept : ""},
{ text : "74 - Haute-Savoie", dept : ""},
{ text : "Eco Savoie Mont blanc", dept : ""},
{ text : "L'Essor Savoyard", dept : ""},
{ text : "L'Hebdo des Savoie", dept : ""},
{ text : "Le Dauphiné Libéré", dept : ""},
{ text : "Le Faucigny", dept : ""},
{ text : "Le Messager", dept : ""},
{ text : "75 - Paris", dept : ""},
{ text : "Affiches Parisiennes", dept : ""},
{ text : "Aujourd'hui en France", dept : ""},
{ text : "L'Auvergnat de Paris", dept : ""},
{ text : "La Croix", dept : ""},
{ text : "La Gazette du Palais", dept : ""},
{ text : "La Loi", dept : ""},
{ text : "La Revue Fiduciaire", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Le Nouvel Economiste", dept : ""},
{ text : "Le Parisien", dept : ""},
{ text : "Le Pèlerin", dept : ""},
{ text : "Le Quotidien Juridique", dept : ""},
{ text : "Les Echos", dept : ""},
{ text : "Les Petites Affiches", dept : ""},
{ text : "Libération", dept : ""},
{ text : "76 - Seine-Maritime", dept : ""},
{ text : "L'Eclaireur Brayon l'éclaireur - La Dépêche", dept : ""},
{ text : "L'Informateur", dept : ""},
{ text : "Le Bulletin de l'Arrondissement de Rouen", dept : ""},
{ text : "Le Courrier Cauchois", dept : ""},
{ text : "Le Journal d'Elbeuf", dept : ""},
{ text : "Le Réveil de Neufchâtel", dept : ""},
{ text : "Les Informations Dieppoises", dept : ""},
{ text : "Paris Normandie", dept : ""},
{ text : "Paris Normandie Havre Dimanche", dept : ""},
{ text : "Union Agricole de la Seine-Maritime", dept : ""},
{ text : "77 - Seine-et-Marne", dept : ""},
{ text : "Horizons - Centre Ile-de-France", dept : ""},
{ text : "L'Eclaireur du Gâtinais et du Centre", dept : ""},
{ text : "La Marne", dept : ""},
{ text : "La République de Seine-et-Marne", dept : ""},
{ text : "Le Moniteur de Seine-et-Marne", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Le Parisien (édition Seine-et-Marne Nord)", dept : ""},
{ text : "Le Parisien (édition Seine-et-Marne Sud)", dept : ""},
{ text : "Le Pays Briard", dept : ""},
{ text : "La Semaine de l'Ile-de-Franc", dept : 78},
{ text : "Le Courrier de Mante", dept : 78},
{ text : "Le Courrier des Yvelines", dept : 78},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : 78},
{ text : "Le Nouvel Economiste", dept : 78},
{ text : "Le Parisien", dept : 78},
{ text : "Les Echos", dept : 78},
{ text : "Toutes les Nouvelles", dept : 78},
{ text : "Agri Information 79", dept : 79},
{ text : "La Concorde", dept : 79},
{ text : "La Nouvelle République du Centre-Ouest", dept : 79},
{ text : "La Nouvelle République du Dimanche édition Deux-Sèvres", dept : 79},
{ text : "Le Courrier de l'Ouest", dept : 79},
{ text : "L'Abeille de la Ternoie", dept: 80},
{ text : "L'Action Agricole Picare", dept: 80},
{ text : "L'Eclaireur du Vimu", dept: 80},
{ text : "L'Informater", dept: 80},
{ text : "Le Bonhomme Picad", dept: 80},
{ text : "Le Courrier Picad", dept: 80},
{ text : "Le Journal d'Abbevile", dept: 80},
{ text : "Le Journal de Hm", dept: 80},
{ text : "Picardie - La Gazete", dept: 80},
{ text : "L'Echo du Tarn", dept : 81},
{ text : "La Dépêche du Midi - édition Tarn", dept : 81},
{ text : "La Dépêche du Midi Dimanche - édition Tarn", dept : 81},
{ text : "La Montagne Noire", dept : 81},
{ text : "Le Journal d'Ici Tarn et Lauragais", dept : 81},
{ text : "Le paysan Tarnais", dept : 81},
{ text : "Le Tarn Libre", dept : 81},
{ text : "82 - Tarn-et-Garonne", dept : ""},
{ text : "La Dépêche du Midi - édition Tarn-et-Garonne", dept : ""},
{ text : "La Gazette du Midi", dept : ""},
{ text : "Le Courrier Français édition Tarn-et-Garonne", dept : ""},
{ text : "Le Petit Journal - Édition Tarn-et-Garonne", dept : ""},
{ text : "83 - Var", dept : ""},
{ text : "La Marseillaise", dept : ""},
{ text : "Le Paysan du Midi", dept : ""},
{ text : "Le Var Information", dept : ""},
{ text : "TPBM - Semaine Provence", dept : ""},
{ text : "Var Matin - Nice Matin", dept : ""},
{ text : "84 - Vaucluse", dept : ""},
{ text : "La Provence", dept : ""},
{ text : "La Tribune", dept : ""},
{ text : "Les Petites Affiches de Vaucluse", dept : ""},
{ text : "TPBM - Semaine Provence", dept : ""},
{ text : "Vaucluse Agricole", dept : ""},
{ text : "Vaucluse Hebdo", dept : ""},
{ text : "Vaucluse Matin", dept : ""},
{ text : "85 - Vendée", dept : ""},
{ text : "L'Echo de l'Ouest édition Vendée", dept : ""},
{ text : "La Vendée Agricole", dept : ""},
{ text : "Le Courrier Vendéen", dept : ""},
{ text : "Le Journal du Pays Yonnais", dept : ""},
{ text : "Les Sables Vendée Journal", dept : ""},
{ text : "Ouest-France", dept : ""},
{ text : "86 - Vienne", dept : ""},
{ text : "Centre Presse", dept : ""},
{ text : "La Nouvelle République du Centre-Ouest", dept : ""},
{ text : "La Nouvelle République du Dimanche édition Vienne", dept : ""},
{ text : "La Vienne Rurale", dept : ""},
{ text : "Le Courrier Français", dept : ""},
{ text : "87 - Haute-Vienne", dept : ""},
{ text : "L'Union Agricole", dept : ""},
{ text : "La Nouvelle Abeille", dept : ""},
{ text : "Le Nouvelliste", dept : ""},
{ text : "Le Populaire du Centre", dept : ""},
{ text : "Le Populaire du Centre Dimanche", dept : ""},
{ text : "88 - Vosges", dept : ""},
{ text : "L'Abeille", dept : ""},
{ text : "L'Echo des Vosges", dept : ""},
{ text : "Le Paysan Vosgien", dept : ""},
{ text : "Les Annonces des Hautes Vosges", dept : ""},
{ text : "Vosges Matin", dept : ""},
{ text : "89 - Yonne", dept : ""},
{ text : "L'Indépendant de l'Yonne", dept : ""},
{ text : "L'Yonne Républicaine", dept : ""},
{ text : "Presse evasion", dept : ""},
{ text : "Terres de Bourgogne", dept : ""},
{ text : "90 - Territoire de Belfort", dept : ""},
{ text : "L'Est Républicain", dept : ""},
{ text : "L'Est Républicain Lundi", dept : ""},
{ text : "La Terre de Chez Nous", dept : ""},
{ text : "MaCommune.Info édition 90 - Territoire de Belfort", dept : ""},
{ text : "91 - Essonne", dept : ""},
{ text : "La Semaine de l'Ile-de-France", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Le Nouvel Economiste", dept : ""},
{ text : "Le Parisien", dept : ""},
{ text : "Le Républicain", dept : ""},
{ text : "Les Echos", dept : ""},
{ text : "92 - Hauts-de-Seine", dept : ""},
{ text : "Affiches Parisiennes", dept : ""},
{ text : "Aujourd'hui en France", dept : ""},
{ text : "L'Echo d'Ile-de-France", dept : ""},
{ text : "La Gazette du Palais", dept : ""},
{ text : "La Loi", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Le Nouvel Economiste", dept : ""},
{ text : "Le Quotidien Juridique", dept : ""},
{ text : "Les Petites Affiches", dept : ""},
{ text : "Libération", dept : ""},
{ text : "93 - Seine-Saint-Denis", dept : ""},
{ text : "Affiches Parisiennes", dept : ""},
{ text : "Aujourd'hui en France", dept : ""},
{ text : "L'Echo d'Ile-de-France", dept : ""},
{ text : "L'Humanité", dept : ""},
{ text : "La Gazette du Palais", dept : ""},
{ text : "La Loi", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtiment", dept : ""},
{ text : "Le Nouvel Economiste", dept : ""},
{ text : "Le Parisien", dept : ""},
{ text : "Le Quotidien Juridique", dept : ""},
{ text : "Les Echos", dept : ""},
{ text : "Les Petites Affiches", dept : ""},
{ text : "Libération", dept : ""},
{ text : "94 - Val-de-Marne", dept : ""},
{ text : "Affiches Parisiennes", dept : ""},
{ text : "L'Echo d'Ile-de-France", dept : ""},
{ text : "L'Humanité", dept : ""},
{ text : "La Gazette du Palais", dept : ""},
{ text : "La Loi", dept : ""},
{ text : "La Vie Judiciaire", dept : ""},
{ text : "Le Moniteur des Travaux Publics et du Bâtimen", dept : ""},
{ text : "Le Nouvel Economiste", dept : ""},
{ text : "Le Parisien", dept : ""},
{ text : "Le Point", dept : ""},
{ text : "Le Publicateur Légal", dept : ""},
{ text : "Le Quotidien Juridique", dept : ""},
{ text : "Les Annonces de la Seine", dept : ""},
{ text : "Les Echos", dept : ""},
{ text : "Les Petites Affiches", dept : ""},
{ text : "Val-de-Marne Infos", dept : ""},
{ text : "95 - Val-d'oise", dept : ""},
{ text : "L'Echo Régional", dept : ""},
{ text : "La Gazette du Val d'Oise", dept : ""},
{ text : "Le Parisien - Val d'Oise matin", dept : ""},
{ text : "Les Echos", dept : ""},
{ text : "971 - Guadeloupe", dept : ""},
{ text : "France Antilles Guadeloupe", dept : ""},
{ text : "Le Courrier de Guadeloupe", dept : ""},
{ text : "Le Probant", dept : ""},
{ text : "Le Progrès Social", dept : ""},
{ text : "Nouvelles Etincelles", dept : ""},
{ text : "Nouvelles Semaine", dept : ""},
{ text : "972 - Martinique", dept : ""},
{ text : "Antilla", dept : ""},
{ text : "France Antilles Martinique", dept : ""},
{ text : "Justice", dept : ""},
{ text : "Le Légis", dept : ""},
{ text : "973 - Guyane", dept : ""},
{ text : "France Antilles Guyane", dept : ""},
{ text : "974 - Réunion", dept : ""},
{ text : "Le Journal de l'Ile de la Réunion", dept : ""},
{ text : "Le Quotidien de la Réunion", dept : ""},
{ text : "Visu", dept : ""},
{ text : "976 - Mayotte", dept : ""},
{ text : "Flash Infos", dept : ""},
{ text : "France Mayotte Matin", dept : ""},
{ text : "Les Nouvelles de Mayotte", dept : ""},
{ text : "Mayotte Hebdo", dept : ""},
{ text : "977 - Saint-Barthélémy", dept : ""},
{ text : "France Antilles Guadeloupe", dept : ""},
{ text : "978 - Saint-Martin", dept : ""},
{ text : "France Antilles Guadeloupe", dept : ""},
{ text : "988 - Nouvelle-Calédonie", dept : ""},
{ text : "Les Nouvelles Calédonienne",dept : ""}
]
</script>